<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Projetos___4</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="2 - Application\Interfaces\" />
    <Folder Include="2 - Application\ViewModel\" />
    <Folder Include="2 - Application\Services\" />
    <Folder Include="3 - Domain\Interfaces\" />
    <Folder Include="3 - Domain\Model\" />
    <Folder Include="4 - Data\Context\" />
    <Folder Include="4 - Data\Repository\" />
  </ItemGroup>

</Project>
